require 'danger-ores.bz.data-updates'
require 'danger-ores.exotic-industries.data-updates'
require 'danger-ores.industrial-revolution-3.data-updates'
require 'danger-ores.krastorio2.data-updates'
require 'danger-ores.omnimatter.data-updates'
require 'danger-ores.pyanodon.data-updates'
require 'danger-ores.vanilla.data-updates'
